// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArxBZmN3FuVBuF64tP3tjTzrkDMn_unPQ',
    appId: '1:287980085729:web:71e2711da0273ebf8472a0',
    messagingSenderId: '287980085729',
    projectId: 'smart-school-47c89',
    authDomain: 'smart-school-47c89.firebaseapp.com',
    storageBucket: 'smart-school-47c89.appspot.com',
    measurementId: 'G-3N017FV3T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23GcS3ffTTf76UhukOjaC7mAXe9mHF_k',
    appId: '1:287980085729:android:778650b0e5c278988472a0',
    messagingSenderId: '287980085729',
    projectId: 'smart-school-47c89',
    storageBucket: 'smart-school-47c89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgsfv_ASZ1j9snyosIaV69olZi2oxYLfQ',
    appId: '1:287980085729:ios:c9ad36293aafc5a78472a0',
    messagingSenderId: '287980085729',
    projectId: 'smart-school-47c89',
    storageBucket: 'smart-school-47c89.appspot.com',
    iosClientId: '287980085729-46icmsajvqht639c5s5lmg6ftailcgk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgsfv_ASZ1j9snyosIaV69olZi2oxYLfQ',
    appId: '1:287980085729:ios:c9ad36293aafc5a78472a0',
    messagingSenderId: '287980085729',
    projectId: 'smart-school-47c89',
    storageBucket: 'smart-school-47c89.appspot.com',
    iosClientId: '287980085729-46icmsajvqht639c5s5lmg6ftailcgk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.id',
  );
}
